spring.application.name=webksz
spring.datasource.url=jdbc:postgresql://localhost:5432/dbwebksz
spring.datasource.username=postgres
spring.datasource.password=sun%2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.docker.compose.enabled=false
spring.liquibase.enabled=true